#!/usr/bin/env bash

DEFAULT_JVM_OPTS="-Xmx64m"

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

ARGS="$@"
NEW_ARGS[0]=''
IDX=0
for ARG in "$@"; do
	case $ARG in
	'-D'*)
			JVM_OPTS="$JVM_OPTS $ARG"
			;;
	*)
			NEW_ARGS[$IDX]="$ARG"
			let IDX=$IDX+1
			;;
	esac
done
ARGS="${NEW_ARGS[@]}"

function splitJvmOpts() {
    JVM_OPTS=("$@")
}
eval splitJvmOpts $DEFAULT_JVM_OPTS $JVM_OPTS

exec "$JAVACMD" "${JVM_OPTS[@]}" -jar /usr/lib/yolo/yolo.jar $ARGS
